# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 124f51876ec217da3978318ee6acdf22146b4213765694806ff2a88b58bc73994c498cbdbd138327198f8815efa2e1bd9e517921fe42079a7650423a0a1dde6b

test:
  secret_key_base: aec94231cbbd6db1ae03c8e98610deabd8c86fb65785e58d2defe7b344c22a4d0e461bb728fb85428334f3141f1e5061a0c83829912633a80c8c0f891f7e499e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
